CREATE TYPE access_profile AS ENUM ('ROLE_CLINICAL', 'ROLE_ADMINISTRATIVE', 'ROLE_MANAGER');
CREATE TYPE medical_specialty AS ENUM ('PSYCHIATRIST', 'PSYCHOLOGIST', 'NURSE', 'SOCIAL_WORKER', 'OCCUPATIONAL_THERAPIST', 'PSYCHOMOTOR_THERAPIST', 'GENERAL_PRACTITIONER', 'CLINICAL_PSYCHOLOGIST', 'OTHER');
CREATE TYPE administrative_role AS ENUM ('RECEPTIONIST', 'ADMINISTRATIVE_ASSISTANT', 'CLINIC_MANAGER', 'IT_SUPPORT', 'HUMAN_RESOURCES', 'FINANCE_OFFICER', 'CLEANING_STAFF', 'SECURITY', 'OTHER');
CREATE TYPE document_type AS ENUM ('PASSPORT', 'NATIONAL_ID', 'DRIVERS_LICENSE', 'RESIDENCE_PERMIT', 'OTHER');
CREATE TYPE country AS ENUM ('BRAZIL', 'UNITED_STATES', 'PORTUGAL', 'UNITED_KINGDOM', 'GERMANY', 'FRANCE', 'SPAIN', 'ITALY', 'CANADA', 'AUSTRALIA', 'JAPAN', 'CHINA', 'OTHER');


CREATE TABLE system_users (
                              id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                              username VARCHAR(255) NOT NULL UNIQUE,
                              password_hash VARCHAR(255) NOT NULL,
                              last_access TIMESTAMP,
                              profile access_profile NOT NULL,
                              dtype VARCHAR(31) NOT NULL
);


CREATE TABLE health_professionals (
                                      id BIGINT PRIMARY KEY,

                                      first_name VARCHAR(255) NOT NULL,
                                      last_name VARCHAR(255) NOT NULL,
                                      birth_date DATE NOT NULL,
                                      phone VARCHAR(255) NOT NULL,
                                      email VARCHAR(255) NOT NULL,

                                      document_type document_type NOT NULL,
                                      document_number VARCHAR(255) NOT NULL,
                                      document_issuing_country country NOT NULL,

                                      specialty medical_specialty NOT NULL,
                                      professional_registration VARCHAR(255) NOT NULL UNIQUE,

                                      care_facility_id BIGINT,

                                      CONSTRAINT fk_health_professional_on_system_user FOREIGN KEY (id) REFERENCES system_users (id)
);


CREATE TABLE administrative_professionals (
                                              id BIGINT PRIMARY KEY,

                                              first_name VARCHAR(255) NOT NULL,
                                              last_name VARCHAR(255) NOT NULL,
                                              birth_date DATE NOT NULL,
                                              phone VARCHAR(255) NOT NULL,
                                              email VARCHAR(255) NOT NULL,

                                              document_type document_type NOT NULL,
                                              document_number VARCHAR(255) NOT NULL,
                                              document_issuing_country country NOT NULL,

                                              role administrative_role NOT NULL,

                                              care_facility_id BIGINT,

                                              CONSTRAINT fk_administrative_professional_on_system_user FOREIGN KEY (id) REFERENCES system_users (id)
);