CREATE TABLE availabilities (
                                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                health_professional_id BIGINT NOT NULL,
                                day_of_week VARCHAR(20) NOT NULL, -- Ex: 'MONDAY', 'TUESDAY'
                                start_time TIME NOT NULL,         -- Ex: '09:00:00'
                                end_time TIME NOT NULL,           -- Ex: '18:00:00'

                                CONSTRAINT fk_availability_on_health_professional FOREIGN KEY (health_professional_id) REFERENCES health_professionals (id)
);