CREATE TABLE care_facilities (
                                 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                 name VARCHAR(255) NOT NULL UNIQUE,
                                 primary_phone VARCHAR(255),
                                 primary_email VARCHAR(255),
                                 address_street VARCHAR(255),
                                 address_city VARCHAR(255),
                                 address_state VARCHAR(255),
                                 address_postal_code VARCHAR(255),
                                 address_country country
);

ALTER TABLE health_professionals
    ADD CONSTRAINT fk_health_professional_on_care_facility FOREIGN KEY (care_facility_id) REFERENCES care_facilities (id);

ALTER TABLE administrative_professionals
    ADD CONSTRAINT fk_administrative_professional_on_care_facility FOREIGN KEY (care_facility_id) REFERENCES care_facilities (id);