CREATE TYPE admission_type AS ENUM ('VOLUNTARY', 'INVOLUNTARY', 'COMPULSORY');
CREATE TYPE alert_status AS ENUM ('OPEN', 'IN_PROGRESS', 'RESOLVED', 'DISMISSED');
CREATE TYPE alert_type AS ENUM ('CRITICAL_MISSED_APPOINTMENT', 'NO_CONTACT', 'BEHAVIORAL_CHANGE', 'MEDICATION_NON_ADHERENCE', 'UPCOMING_LEGAL_REVIEW');
CREATE TYPE clinical_event_type AS ENUM ('DIAGNOSIS_RECORD', 'SURGERY', 'ALLERGY_RECORD', 'CHRONIC_DISEASE_RECORD', 'PREVIOUS_TREATMENT', 'HOSPITALIZATION_RECORD');
CREATE TYPE legal_review_status AS ENUM ('SCHEDULED', 'PENDING_DECISION', 'APPROVED', 'REJECTED');
CREATE TYPE severity_level AS ENUM ('LOW', 'MEDIUM', 'HIGH', 'CRITICAL');
CREATE TYPE treatment_plan_status AS ENUM ('ACTIVE', 'COMPLETED', 'CANCELLED', 'UNDER_REVIEW');


CREATE TABLE patients (
                          id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                          care_facility_id BIGINT,
                          first_name VARCHAR(255) NOT NULL,
                          last_name VARCHAR(255) NOT NULL,
                          birth_date DATE NOT NULL,
                          phone VARCHAR(255) NOT NULL,
                          email VARCHAR(255),
                          document_type VARCHAR(255) NOT NULL,
                          document_number VARCHAR(255) NOT NULL,
                          document_issuing_country VARCHAR(255) NOT NULL,
                          emergency_contact_full_name VARCHAR(255),
                          emergency_contact_relationship VARCHAR(255),
                          emergency_contact_phone VARCHAR(255),
                          CONSTRAINT fk_patient_on_care_facility FOREIGN KEY (care_facility_id) REFERENCES care_facilities (id)
);

CREATE TABLE admissions (
                            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                            patient_id BIGINT NOT NULL,
                            type VARCHAR(255) NOT NULL,
                            admission_date TIMESTAMP NOT NULL,
                            discharge_date TIMESTAMP,
                            reason TEXT,
                            ward VARCHAR(255),
                            CONSTRAINT fk_admission_on_patient FOREIGN KEY (patient_id) REFERENCES patients (id)
);

CREATE TABLE legal_reviews (
                               id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                               admission_id BIGINT NOT NULL,
                               review_date DATE,
                               reviewer_notes TEXT,
                               status VARCHAR(255) NOT NULL,
                               CONSTRAINT fk_legal_review_on_admission FOREIGN KEY (admission_id) REFERENCES admissions (id)
);

CREATE TABLE alerts (
                        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        patient_id BIGINT NOT NULL,
                        assigned_to_id BIGINT,
                        type VARCHAR(255) NOT NULL,
                        status VARCHAR(255) NOT NULL,
                        message TEXT NOT NULL,
                        created_at TIMESTAMP NOT NULL,
                        resolved_at TIMESTAMP,
                        CONSTRAINT fk_alert_on_patient FOREIGN KEY (patient_id) REFERENCES patients (id),
                        CONSTRAINT fk_alert_on_health_professional FOREIGN KEY (assigned_to_id) REFERENCES health_professionals (id)
);

CREATE TABLE patient_events (
                                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                patient_id BIGINT NOT NULL,
                                event_date_time TIMESTAMP NOT NULL,
                                description TEXT,
                                dtype VARCHAR(31) NOT NULL,
                                CONSTRAINT fk_patient_event_on_patient FOREIGN KEY (patient_id) REFERENCES patients (id)
);

CREATE TABLE medical_history_events (
                                        id BIGINT PRIMARY KEY,
                                        event_type VARCHAR(255) NOT NULL,
                                        CONSTRAINT fk_mhe_on_pe FOREIGN KEY (id) REFERENCES patient_events (id)
);

CREATE TABLE crisis_events (
                               id BIGINT PRIMARY KEY,
                               reported_by_id BIGINT,
                               severity VARCHAR(255) NOT NULL,
                               action_taken TEXT,
                               outcome TEXT,
                               CONSTRAINT fk_ce_on_pe FOREIGN KEY (id) REFERENCES patient_events (id),
                               CONSTRAINT fk_ce_on_health_professional FOREIGN KEY (reported_by_id) REFERENCES health_professionals (id)
);

CREATE TABLE consultation_sessions (
                                       id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                       patient_id BIGINT NOT NULL,
                                       health_professional_id BIGINT NOT NULL,
                                       session_date_time TIMESTAMP NOT NULL,
                                       clinical_notes TEXT,
                                       CONSTRAINT fk_consultation_on_patient FOREIGN KEY (patient_id) REFERENCES patients (id),
                                       CONSTRAINT fk_consultation_on_health_professional FOREIGN KEY (health_professional_id) REFERENCES health_professionals (id)
);

CREATE TABLE prescriptions (
                               id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                               consultation_session_id BIGINT NOT NULL,
                               medication_name VARCHAR(255) NOT NULL,
                               dosage VARCHAR(255),
                               instructions TEXT,
                               prescription_date DATE NOT NULL,
                               duration_in_days INT NOT NULL,
                               CONSTRAINT fk_prescription_on_consultation FOREIGN KEY (consultation_session_id) REFERENCES consultation_sessions (id)
);

CREATE TABLE diagnoses (
                           id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                           patient_id BIGINT NOT NULL,
                           diagnosis_code VARCHAR(255),
                           description VARCHAR(255) NOT NULL,
                           diagnosis_date DATE NOT NULL,
                           is_primary_diagnosis BOOLEAN NOT NULL,
                           CONSTRAINT fk_diagnosis_on_patient FOREIGN KEY (patient_id) REFERENCES patients (id)
);

CREATE TABLE treatment_plans (
                                 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                 patient_id BIGINT NOT NULL UNIQUE,
                                 supervising_professional_id BIGINT,
                                 status VARCHAR(255) NOT NULL,
                                 objectives TEXT,
                                 start_date DATE NOT NULL,
                                 expected_end_date DATE,
                                 CONSTRAINT fk_treatment_plan_on_patient FOREIGN KEY (patient_id) REFERENCES patients (id),
                                 CONSTRAINT fk_treatment_plan_on_health_professional FOREIGN KEY (supervising_professional_id) REFERENCES health_professionals (id)
);