CREATE TABLE audit_logs (
                            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                            timestamp TIMESTAMP NOT NULL,
                            username VARCHAR(255) NOT NULL,
                            action VARCHAR(255) NOT NULL,
                            details TEXT
);